#!/bin/sh

prod_user=oerttrprd61
test_user=oerttrtst61
prod_db=technotrading
test_db=test61

sudo -u $test_user /etc/init.d/$test_user stop
sudo -u $test_user psql -c "drop database $test_db" template1
sudo -u $test_user psql -c "create database $test_db" template1
sudo -u $prod_user pg_dump --format=c $prod_db | sudo -u $test_user pg_restore --no-owner --dbname=$test_db
sudo -u $test_user psql -c "update ir_cron set active=False" $test_db
sudo -u $test_user psql -c "update external_referential set location='http://31.3.99.103:8300/';" $test_db
sudo -u $test_user /etc/init.d/$test_user start
