import ast
import re
import pprint

""" Process the log generated by orm_audit_write """

f = open("/home/oerttrtst61/oerttrtst61.log-ter-analyse-2013-09-24")
fields = {}

for line in f:
    res = re.search(r'osv: Updating ([^\\]+)\\#[0-9]+: (.*)', line)
    if res:
        model = res.group(1)
        data = ast.literal_eval(res.group(2))
        for key in data.keys():
            if str(key) not in fields.setdefault(model, []):
                fields[model].append(str(key))
f.close()

for model in fields:
    print "%s: %s" % (model, pprint.pformat(sorted(fields[model])))
